### ISSUE TITLE
There are no Enterprise Mobility + Security licenses in the lab

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/MS-4006-Copilot-for-Microsoft-365-for-Administrators#2]
Learning Path 2 - Lab 2 - Exercise 1
# Module: 2
#### Step: 3

Description of issue: There are no Enterprise Mobility + Security licenses in the lab

**Comment by tfrink** [comment]
This was a recent change to the trial tenant. The recent lab updates that were just released fixed this issue. Thank you however for recognizing this.
